logging:
  level:
    org:
      springframework: INFO 
odata:
  api:
    version: "0.1.0-alpha.1"
    path_prefix: "v0"
  jpa:
    punit_name: "com.sap.cloud.cmp.ord.service" # used in persistance.xml for Java EE, but in Spring (like here) only used as namespace of the OData service
    request_mapping_path: "open-resource-discovery-service/${odata.api.path_prefix}"
    root_packages: "com.sap.cloud.cmp.ord.service"
static:
  api:
    version: "0.1.0-alpha.1"
    path_prefix: "v0"
  request_mapping_path: "open-resource-discovery-static/${static.api.path_prefix}"
server:
  port: 8080
  default_response_type: "xml"
spring:
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.orm.jpa.HibernateMetricsAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    password: pgsql@12345
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db_name}
    port: 5432
    host: localhost
    db_name: compass
    username: postgres
    hikari:
      minimumIdle: 1
      idleTimeout: 60000
      maximumPoolSize: 5
  servlet:
    multipart:
      enabled: false
springdoc:
  openapi-version: "3.0.3"
  custom-base-path: "/open-resource-discovery-docs"
  swagger-ui:
    path: "${springdoc.custom-base-path}/swagger-ui"
  api-docs:
    path: "${springdoc.custom-base-path}/api-docs"
    pathsToMatch: "/${static.request_mapping_path}/**"

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      group:
        readiness:
          include: "schemaCompatibility,db"
http:
  headers:
    correlationId: x-request-id
destination_fetcher:
  reload_url: null
  sensitive_data_url: null
  tenant_header: Tenant
  sensitive_data_query_param: name
  auth_token_path: /tmp/ord-service-account.txt
  skip_ssl_validation: false
